// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;
import 'package:universal_platform/universal_platform.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (UniversalPlatform.isWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClLK_7mRZJD-958MgTK-i3pAWIU_lEfjg',
    appId: '1:676767716729:web:d06c3d6191994bf0dccba8',
    messagingSenderId: '676767716729',
    projectId: 'skillpe-be2cf',
    authDomain: 'skillpe-be2cf.firebaseapp.com',
    storageBucket: 'skillpe-be2cf.firebasestorage.app',
    measurementId: 'G-54GG6JTB2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6iv6hm0G6npS0Y-vifZEowhiBP-ZBP3s',
    appId: '1:676767716729:android:17ca454fdc37cac1dccba8',
    messagingSenderId: '676767716729',
    projectId: 'skillpe-be2cf',
    storageBucket: 'skillpe-be2cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALhekiz0rV3oictPL3H3m82DLW7iFpGlY',
    appId: '1:676767716729:ios:ed5e08d17abe7aeadccba8',
    messagingSenderId: '676767716729',
    projectId: 'skillpe-be2cf',
    storageBucket: 'skillpe-be2cf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );
}
